apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
stringData:
  database-url: "postgresql://user:password@user-db:5432/userdb"
  secret-key: "supersecretkey123changethis"
---
apiVersion: v1
kind: Secret
metadata:
  name: product-service-secrets
type: Opaque
stringData:
  database-url: "postgresql://user:password@product-db:5432/productdb"
---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
type: Opaque
stringData:
  database-url: "postgresql://user:password@order-db:5432/orderdb"